[package]
name = "ruby-stacktrace"
version = "0.1.0"
authors = ["Julia Evans <julia@jvns.ca>"]

[dependencies]
libc = "0.2.15"
regex = "0.1"
term = "0.2"
clap = "2"
byteorder = "0.5"
leb128 = "0.2.1"
rand = "0.3"
fnv = "1.0.3"
gimli={git="https://github.com/fitzgen/gimli.git"}
elf = "0.0.9"
log = "0.3.6"
env_logger = "0.3.4"
